//
//  ShowImageInteractor.swift
//  Rentateam
//
//  Created by Vitalii Sosin on 11.02.2021.
//  Copyright (c) 2021 SosinVitalii.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowImageBusinessLogic {
    func doSomething(request: ShowImage.Something.Request)
}

protocol ShowImageDataStore {
    //var name: String { get set }
}

class ShowImageInteractor: ShowImageBusinessLogic, ShowImageDataStore {
    
    var presenter: ShowImagePresentationLogic?
    var worker: ShowImageWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ShowImage.Something.Request) {
        worker = ShowImageWorker()
        worker?.doSomeWork()
        
        let response = ShowImage.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
