//
//  ShowImageViewController.swift
//  Rentateam
//
//  Created by Vitalii Sosin on 12.02.2021.
//  Copyright (c) 2021 SosinVitalii.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ShowImageViewController: UIViewController {

    override func loadView() {
        view = ShowImageView()
    }
    
    private var showImageView: ShowImageView {
        guard let view = view as? ShowImageView else { fatalError("Could not create a view") }
        return view
    }
    
    var interactor: ShowImageStoreProtocol?
    var router: ShowImageDataPassing?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    private func setupUI() {
        showImageView.imageView.image = interactor?.selectedCell?.image
        showImageView.dateLabel.text = "Дата скачивания: \(interactor?.selectedCell?.date ?? "отсутствует")"
    }
}
