//
//  ImageListPresenter.swift
//  Rentateam
//
//  Created by Vitalii Sosin on 12.02.2021.
//  Copyright (c) 2021 SosinVitalii.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListPresenterLogic: AnyObject {
    func presentData(data: Pixabay)
}

final class ImageListPresenter {
    weak var viewController: ImageListDisplayLogic?
}

extension ImageListPresenter: ImageListPresenterLogic {
    
    func presentData(data: Pixabay) {
        let viewModel = data.hits.map { model -> ImageListViewModel in
                guard let imageData = ImageManager.shared.getImageData(from: model.previewURL) else { fatalError("Could not get imageData") }
                guard let image = UIImage(data: imageData) else { fatalError("Could not get image") }
            let cellModel = ImageListViewModel(image: image, date: getDateStringFull())
                return cellModel
            }
            self.viewController?.fetchedArray(elements: viewModel)
    }
}
