//
//  ImageListViewController.swift
//  Rentateam
//
//  Created by Vitalii Sosin on 11.02.2021.
//  Copyright (c) 2021 SosinVitalii.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListDisplayLogic: class {
    func displaySomething(viewModel: ImageList.Something.ViewModel)
}

class ImageListViewController: UITableViewController, ImageListDisplayLogic {
    
    //@IBOutlet private var nameTextField: UITextField!
    
    var interactor: ImageListBusinessLogic?
    var router: (NSObjectProtocol & ImageListRoutingLogic & ImageListDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        
        view.backgroundColor = .yellow
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Do something
    
    func doSomething() {
        let request = ImageList.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ImageList.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ImageListInteractor()
        let presenter = ImageListPresenter()
        let router = ImageListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
