//
//  ImageListRouter.swift
//  Rentateam
//
//  Created by Vitalii Sosin on 12.02.2021.
//  Copyright (c) 2021 SosinVitalii.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListRouterLogic: AnyObject {
    func navigateToShowImage(viewModel: ImageListViewModel)
}

final class ImageListRouter {
    weak var viewController: UIViewController?
}

extension ImageListRouter: ImageListRouterLogic {
    func navigateToShowImage(viewModel: ImageListViewModel) {
        guard let showImageVC = ModuleBuilder.createShowImageVC() as? ShowImageViewController else { fatalError("Could not create ShowImageVC")}
        showImageVC.router?.dataStore?.selectedCell = viewModel
        viewController?.navigationController?.pushViewController(showImageVC, animated: true)
    }
}
